/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KAUBookStoreSystem;
import static cpit251_project.buss_alhuda.marketing;
import cpit380practice.Picture;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
/**
 *
 * @author manar
 */
public class buss_alhafez extends javax.swing.JFrame {
static Picture marketing;
static Picture marketing1;
static Picture admins;
static Picture accounting;

//to check availablity of book
static boolean avamarketing;
static boolean avamarketing1;
static boolean avaadmins;
static boolean avaaccounting;
//books
static Book book1;
static Book book2;
static Book book3;
static Book book4;
static  ArrayList<Book> cartt;

    /**
     * Creates new form buss_alhafez
     */
    public buss_alhafez() throws FileNotFoundException, IOException {
        initComponents();
        cart.setBackground(new Color(255, 255, 255, 100));
        orders.setBackground(new Color(255, 255, 255, 100));
        info.setBackground(new Color(255, 255, 255, 100));
         File file = new File("Book.txt");
        Scanner read = new Scanner (file);
        boolean ava=false;
      
        String line = Files.readAllLines(Paths.get("Book.txt")).get(0);
        System.out.println(line);
        Book_linkedlist bl = new Book_linkedlist();
        Book book = new Book();
      while(read.hasNext()){
          switch(read.next()){
              case "1000" :              
        String info [] = read.next().split(",");
         marketing = new Picture ("marketing.jpg");
         String bookName = info[1] + " " + info[2];
        if(book.isAvailable(info[6])==true){
            avamarketing=true;
        }else{
            avamarketing=false;
        }
        
        jmark1.setIcon(new ImageIcon(marketing.getImage().getScaledInstance(160, 160, 1)));
         book1 = new Book(bookName,Integer.parseInt(info[3]),Integer.parseInt(info[4]),avamarketing,info[5],marketing);
         jLabel8.setText(book1.getPrice()+"");
        bl.addBook(book1);
        break;
              case "1001" :
    String info1 [] = read.next().split(",");
        accounting = new Picture ("accounting.jpg");
        if(book.isAvailable(info1[6])==true){
            avaaccounting=true;
        }else{
            avaaccounting=false;
        }
         book2 = new Book(info1[1],Integer.parseInt(info1[2]),Integer.parseInt(info1[3]),avaaccounting,info1[5],accounting);
                  jLabel9.setText(book2.getPrice()+"");
           jaccounting.setIcon(new ImageIcon(accounting.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book2);
        break;
              case "1002" :  String info2 [] = read.next().split(",");
         marketing1 = new Picture ("marketing1.jpg");
        if(book.isAvailable(info2[6])==true){
            avamarketing1=true;
          
        }else{
            avamarketing1=false;
      
        }
       
         book3 = new Book(info2[1],Integer.parseInt(info2[2]),Integer.parseInt(info2[3]),avamarketing1,info2[5],marketing1);
                  jLabel10.setText(book3.getPrice()+"");
           jmark2.setIcon(new ImageIcon(marketing1.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book3);
         break;
            case "1003" :  String info3 [] = read.next().split(",");
         admins = new Picture ("adminis.jpeg");
        if(book.isAvailable(info3[6])==true){
            avaadmins=true;
        }else{
            avaadmins=false;
        }
         book4 = new Book(info3[1],Integer.parseInt(info3[2]),Integer.parseInt(info3[3]),avaadmins,info3[5],admins);
                  jLabel11.setText(book4.getPrice()+"");
           jadmins.setIcon(new ImageIcon(admins.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book4);break;
        
          }
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orders = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jmark1 = new javax.swing.JLabel();
        incmark1 = new javax.swing.JButton();
        decarab201 = new javax.swing.JButton();
        arab201_price = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jadmins = new javax.swing.JLabel();
        incadmin2 = new javax.swing.JButton();
        isls401_price = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        decisls401 = new javax.swing.JButton();
        jmark2 = new javax.swing.JLabel();
        incmark2 = new javax.swing.JButton();
        isls201_price = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        decisls201 = new javax.swing.JButton();
        incaccounting = new javax.swing.JButton();
        isls301_price = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        deisls301 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jaccounting = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("ثة");

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cart.setBackground(new java.awt.Color(255, 204, 102));
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cart");

        javax.swing.GroupLayout cartLayout = new javax.swing.GroupLayout(cart);
        cart.setLayout(cartLayout);
        cartLayout.setHorizontalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartLayout.setVerticalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        orders.setBackground(new java.awt.Color(255, 204, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Orders");

        javax.swing.GroupLayout ordersLayout = new javax.swing.GroupLayout(orders);
        orders.setLayout(ordersLayout);
        ordersLayout.setHorizontalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(78, 78, 78))
        );
        ordersLayout.setVerticalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        info.setBackground(new java.awt.Color(255, 204, 102));
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Information");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(search);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        jLabel5.setText("search");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jmark1.setBackground(new java.awt.Color(102, 102, 255));
        jmark1.setForeground(new java.awt.Color(255, 51, 51));
        jmark1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmark1MouseClicked(evt);
            }
        });

        incmark1.setBackground(new java.awt.Color(255, 255, 204));
        incmark1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incmark1.setText("+");
        incmark1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incmark1MouseClicked(evt);
            }
        });
        incmark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incmark1ActionPerformed(evt);
            }
        });

        decarab201.setBackground(new java.awt.Color(255, 255, 204));
        decarab201.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decarab201.setText("-");

        arab201_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("39 SR");

        javax.swing.GroupLayout arab201_priceLayout = new javax.swing.GroupLayout(arab201_price);
        arab201_price.setLayout(arab201_priceLayout);
        arab201_priceLayout.setHorizontalGroup(
            arab201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab201_priceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        arab201_priceLayout.setVerticalGroup(
            arab201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab201_priceLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jadmins.setBackground(new java.awt.Color(102, 102, 255));
        jadmins.setForeground(new java.awt.Color(255, 51, 51));
        jadmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadminsMouseClicked(evt);
            }
        });

        incadmin2.setBackground(new java.awt.Color(255, 255, 204));
        incadmin2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incadmin2.setText("+");
        incadmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incadmin2ActionPerformed(evt);
            }
        });

        isls401_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("31 SR");

        javax.swing.GroupLayout isls401_priceLayout = new javax.swing.GroupLayout(isls401_price);
        isls401_price.setLayout(isls401_priceLayout);
        isls401_priceLayout.setHorizontalGroup(
            isls401_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls401_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        isls401_priceLayout.setVerticalGroup(
            isls401_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls401_priceLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decisls401.setBackground(new java.awt.Color(255, 255, 204));
        decisls401.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisls401.setText("-");

        jmark2.setBackground(new java.awt.Color(102, 102, 255));
        jmark2.setForeground(new java.awt.Color(255, 51, 51));
        jmark2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmark2MouseClicked(evt);
            }
        });

        incmark2.setBackground(new java.awt.Color(255, 255, 204));
        incmark2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incmark2.setText("+");
        incmark2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incmark2MouseClicked(evt);
            }
        });
        incmark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incmark2ActionPerformed(evt);
            }
        });

        isls201_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("31 SR");

        javax.swing.GroupLayout isls201_priceLayout = new javax.swing.GroupLayout(isls201_price);
        isls201_price.setLayout(isls201_priceLayout);
        isls201_priceLayout.setHorizontalGroup(
            isls201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls201_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        isls201_priceLayout.setVerticalGroup(
            isls201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls201_priceLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decisls201.setBackground(new java.awt.Color(255, 255, 204));
        decisls201.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisls201.setText("-");

        incaccounting.setBackground(new java.awt.Color(255, 255, 204));
        incaccounting.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incaccounting.setText("+");
        incaccounting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incaccountingActionPerformed(evt);
            }
        });

        isls301_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("31 SR");

        javax.swing.GroupLayout isls301_priceLayout = new javax.swing.GroupLayout(isls301_price);
        isls301_price.setLayout(isls301_priceLayout);
        isls301_priceLayout.setHorizontalGroup(
            isls301_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls301_priceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        isls301_priceLayout.setVerticalGroup(
            isls301_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls301_priceLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deisls301.setBackground(new java.awt.Color(255, 255, 204));
        deisls301.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deisls301.setText("-");

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setForeground(new java.awt.Color(255, 153, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("AR JULIAN", 0, 24)); // NOI18N
        jLabel12.setText("home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jaccounting.setBackground(new java.awt.Color(102, 102, 255));
        jaccounting.setForeground(new java.awt.Color(255, 51, 51));
        jaccounting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jaccountingMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 204, 153));
        jPanel6.setForeground(new java.awt.Color(255, 153, 51));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("AR JULIAN", 0, 24)); // NOI18N
        jLabel6.setText("Back");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(441, 441, 441)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(deisls301)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isls301_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incaccounting))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(615, 615, 615)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(decarab201)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(arab201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(incmark1))
                                    .addComponent(jmark1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7))
                            .addComponent(jaccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jmark2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(decisls401)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isls401_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incmark2)))
                        .addGap(60, 60, 60)
                        .addComponent(decisls201)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isls201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incadmin2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(816, 816, 816)
                        .addComponent(jadmins, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jmark1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(arab201_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incmark1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decarab201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jadmins, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(jmark2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(isls401_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decisls401, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incmark2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decisls201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(isls201_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incadmin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jaccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(incaccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(deisls301, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(isls301_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incmark1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incmark1MouseClicked

        if(avamarketing==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16))); 
        Cart cr= new Cart();
        book1.setQuantity(book1.getQuantity()+1);
          cr.addToCart(book1);
          try {
                cr.PrintCart();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(buss_alhafez.class.getName()).log(Level.SEVERE, null, ex);
            }
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incmark1MouseClicked

    private void incmark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incmark1ActionPerformed

        if(avamarketing==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
            
     Cart cr2 = new Cart();
        book1.setQuantity(book1.getQuantity()+1);
        cr2.setProductQuantity(book1.getQuantity());
          cr2.calTotal(book1.getPrice(),book1.getQuantity());
           
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);

}
    }//GEN-LAST:event_incmark1ActionPerformed

    private void incadmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incadmin2ActionPerformed

        if(avaadmins==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));   
        //cart
Cart cr = new Cart();
    
          Cart cr2 = new Cart();
        book2.setQuantity(book2.getQuantity()+1);
        cr2.setProductQuantity(book2.getQuantity());
          
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incadmin2ActionPerformed

    private void incmark2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incmark2MouseClicked

        if(avamarketing1==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incmark2MouseClicked

    private void incmark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incmark2ActionPerformed

        if(avamarketing1==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16))); //cart
Cart cr2 = new Cart();
        book3.setQuantity(book3.getQuantity()+1);
        cr2.setProductQuantity(book3.getQuantity());
          
          
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incmark2ActionPerformed

    private void incaccountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incaccountingActionPerformed

        if(avaaccounting==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16))); 
       book4.setQuantity(book4.getQuantity()+1);//cart
Cart cr2 = new Cart();
        book4.setQuantity(book4.getQuantity()+1);
        cr2.setProductQuantity(book4.getQuantity());
          
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incaccountingActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        selectbookstore sn = new selectbookstore();
        sn.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jmark1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmark1MouseClicked
      try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book1);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jmark1MouseClicked

    private void jmark2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmark2MouseClicked
       try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book3);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jmark2MouseClicked

    private void jaccountingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaccountingMouseClicked
     try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book2);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jaccountingMouseClicked

    private void jadminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadminsMouseClicked
         try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book4);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jadminsMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
           String searchBook = search.getText();
    
        SearchBook_Interface bi = new SearchBook_Interface();
        switch (searchBook) {
  
            case "marketing":
                bi.displayBook(book1);
                bi.setVisible(true);
                break;
     
            case "accounting":
                bi.displayBook(book2);
                bi.setVisible(true);
                break;
       
            case "marketing research":
                bi.displayBook(book3);
                bi.setVisible(true);
                break;
            case "administration":
                       bi.displayBook(book4);
                bi.setVisible(true);
                break;
                         default: SearchBook_noresults n = new SearchBook_noresults();
                  n.setVisible(true);
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseClicked
     cart_interface cr;
    try {
        cr = new cart_interface();
           cr.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(buss_alhafez.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(buss_alhafez.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    }//GEN-LAST:event_cartMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        selectbookstore sn = new selectbookstore();
        sn.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
studentInfo sd;
    try {
        sd = new studentInfo();sd.setVisible(true);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(buss_alhafez.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_infoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buss_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buss_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buss_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buss_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
                try {
                    new buss_alhafez().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(buss_alhafez.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(buss_alhafez.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arab201_price;
    private javax.swing.JPanel cart;
    private javax.swing.JButton decarab201;
    private javax.swing.JButton decisls201;
    private javax.swing.JButton decisls401;
    private javax.swing.JButton deisls301;
    private javax.swing.JButton incaccounting;
    private javax.swing.JButton incadmin2;
    private javax.swing.JButton incmark1;
    private javax.swing.JButton incmark2;
    private javax.swing.JPanel info;
    private javax.swing.JPanel isls201_price;
    private javax.swing.JPanel isls301_price;
    private javax.swing.JPanel isls401_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jaccounting;
    private javax.swing.JLabel jadmins;
    private javax.swing.JLabel jmark1;
    private javax.swing.JLabel jmark2;
    private javax.swing.JPanel orders;
    private javax.swing.JTextPane search;
    // End of variables declaration//GEN-END:variables
}
