/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KAUBookStoreSystem;
import static cpit251_project.fcit_alhuda.object;
import static cpit251_project.fcit_alkha.object;
import cpit380practice.Picture;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
/**
 *
 * @author manar
 */
public class fcit_alhafez extends javax.swing.JFrame {
//pictures of the book
static Picture object;
static Picture network;
static Picture graphics;
static Picture skills;
static Picture architecture;

//to check availablity of book
static boolean avaobject;
static boolean avanetwork;
static boolean avagraphics;
static boolean avaskills;
static boolean avaarchitecture;
//books
static Book book1;
static Book book2;
static Book book3;
static Book book4;
static Book book5;
    /**
     * Creates new form fcit_alhafez
     */
    public fcit_alhafez() throws FileNotFoundException {
        initComponents();
             cart.setBackground(new Color(255, 255, 255, 100));
        orders.setBackground(new Color(255, 255, 255, 100));
        info.setBackground(new Color(255, 255, 255, 100));
          File file = new File("Book.txt");
        Scanner read = new Scanner (file);
        boolean ava=false;
        Book_linkedlist bl = new Book_linkedlist();
        Book book = new Book();
      while(read.hasNext()){
          switch(read.next()){
              case "800" : 
        String info [] = read.next().split(",");
        String bookName = info[1] + " " + info[2] + " " + info[3] + " " + info[4];
        object = new Picture ("objectori.jpg");
        if(book.isAvailable(info[9])==true){
            avaobject=true;
        }else{
            avaobject=false;
        }
        jobject.setIcon(new ImageIcon(object.getImage().getScaledInstance(160, 160, 1)));
         book1 = new Book(bookName,info[5],info[6],avaobject,info[7],object);
        bl.addBook(book1);
        break;
              case "801" :
    String info1 [] = read.next().split(",");
         network = new Picture ("topdown.jpg");
         String bookName1 = info1[1] + " " + info1[2] + " " + info1[3];
        if(book.isAvailable(info1[8])==true){
            avanetwork=true;
        }else{
            avanetwork=false;
        }
         book2 = new Book(bookName1,info1[4],info1[5],avanetwork,info1[6],network);
           jnetwork.setIcon(new ImageIcon(network.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book2);
        break;
              case "802" :  String info2 [] = read.next().split(",");
         graphics = new Picture ("graphics.jpeg");
        if(book.isAvailable(info2[6])==true){
            avagraphics=true;
          
        }else{
            avagraphics=false;
      
        }
       
         book3 = new Book(info2[1],info2[2],info2[3],avagraphics,info2[4],graphics);
           jgraphics.setIcon(new ImageIcon(graphics.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book3);
         break;
            case "803" :  String info3 [] = read.next().split(",");
         skills = new Picture ("computer.jpg");
         String bookName3 = info3[1] + " " + info3[2];
                
        if(book.isAvailable(info3[7])==true){
            avaskills=true;
        }else{
            avaskills=false;
        }
          book4 = new Book(bookName3,info3[3],info3[4],ava,info3[5],skills);
           jcomskills.setIcon(new ImageIcon(skills.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book4);break;
            case "804" :  String info4 [] = read.next().split(",");
            String bookName5 = info4[1] + "  " + info4[2] + " " +info4[3];
         architecture = new Picture ("architecture.jpg");
    
        if(book.isAvailable(info4[8])==true){
            avaarchitecture=true;
        }else{
            avaarchitecture=false;
        }
         book5 = new Book(bookName5,info4[4],info4[5],avaarchitecture,info4[6],architecture);
           jarchitecture.setIcon(new ImageIcon(architecture.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book5);break;
    
          }
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orders = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jobject = new javax.swing.JLabel();
        incobject = new javax.swing.JButton();
        decarab201 = new javax.swing.JButton();
        arab201_price = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jarchitecture = new javax.swing.JLabel();
        incarchitecture = new javax.swing.JButton();
        isls401_price = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        decisls401 = new javax.swing.JButton();
        jnetwork = new javax.swing.JLabel();
        incnetwork = new javax.swing.JButton();
        isls201_price = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        decisls201 = new javax.swing.JButton();
        jgraphics = new javax.swing.JLabel();
        inccomskills = new javax.swing.JButton();
        isls301_price = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        deisls301 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jcomskills = new javax.swing.JLabel();
        incgraphics = new javax.swing.JButton();
        decarab101 = new javax.swing.JButton();
        arab101_price = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("ثة");

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cart.setBackground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cart");

        javax.swing.GroupLayout cartLayout = new javax.swing.GroupLayout(cart);
        cart.setLayout(cartLayout);
        cartLayout.setHorizontalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartLayout.setVerticalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        orders.setBackground(new java.awt.Color(255, 204, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Orders");

        javax.swing.GroupLayout ordersLayout = new javax.swing.GroupLayout(orders);
        orders.setLayout(ordersLayout);
        ordersLayout.setHorizontalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(78, 78, 78))
        );
        ordersLayout.setVerticalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        info.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Information");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(search);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        jLabel5.setText("search");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jobject.setBackground(new java.awt.Color(102, 102, 255));
        jobject.setForeground(new java.awt.Color(255, 51, 51));
        jobject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobjectMouseClicked(evt);
            }
        });

        incobject.setBackground(new java.awt.Color(255, 255, 204));
        incobject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incobject.setText("+");
        incobject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incobjectMouseClicked(evt);
            }
        });

        decarab201.setBackground(new java.awt.Color(255, 255, 204));
        decarab201.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decarab201.setText("-");

        arab201_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("39 SR");

        javax.swing.GroupLayout arab201_priceLayout = new javax.swing.GroupLayout(arab201_price);
        arab201_price.setLayout(arab201_priceLayout);
        arab201_priceLayout.setHorizontalGroup(
            arab201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab201_priceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        arab201_priceLayout.setVerticalGroup(
            arab201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab201_priceLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jarchitecture.setBackground(new java.awt.Color(102, 102, 255));
        jarchitecture.setForeground(new java.awt.Color(255, 51, 51));
        jarchitecture.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jarchitectureMouseDragged(evt);
            }
        });
        jarchitecture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jarchitectureMouseClicked(evt);
            }
        });

        incarchitecture.setBackground(new java.awt.Color(255, 255, 204));
        incarchitecture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incarchitecture.setText("+");
        incarchitecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incarchitectureActionPerformed(evt);
            }
        });

        isls401_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("31 SR");

        javax.swing.GroupLayout isls401_priceLayout = new javax.swing.GroupLayout(isls401_price);
        isls401_price.setLayout(isls401_priceLayout);
        isls401_priceLayout.setHorizontalGroup(
            isls401_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls401_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        isls401_priceLayout.setVerticalGroup(
            isls401_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls401_priceLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decisls401.setBackground(new java.awt.Color(255, 255, 204));
        decisls401.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisls401.setText("-");

        jnetwork.setBackground(new java.awt.Color(102, 102, 255));
        jnetwork.setForeground(new java.awt.Color(255, 51, 51));
        jnetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnetworkMouseClicked(evt);
            }
        });

        incnetwork.setBackground(new java.awt.Color(255, 255, 204));
        incnetwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incnetwork.setText("+");
        incnetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incnetworkMouseClicked(evt);
            }
        });
        incnetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incnetworkActionPerformed(evt);
            }
        });

        isls201_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("31 SR");

        javax.swing.GroupLayout isls201_priceLayout = new javax.swing.GroupLayout(isls201_price);
        isls201_price.setLayout(isls201_priceLayout);
        isls201_priceLayout.setHorizontalGroup(
            isls201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls201_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        isls201_priceLayout.setVerticalGroup(
            isls201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls201_priceLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decisls201.setBackground(new java.awt.Color(255, 255, 204));
        decisls201.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisls201.setText("-");

        jgraphics.setBackground(new java.awt.Color(102, 102, 255));
        jgraphics.setForeground(new java.awt.Color(255, 51, 51));
        jgraphics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jgraphicsMouseClicked(evt);
            }
        });

        inccomskills.setBackground(new java.awt.Color(255, 255, 204));
        inccomskills.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inccomskills.setText("+");
        inccomskills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inccomskillsActionPerformed(evt);
            }
        });

        isls301_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("31 SR");

        javax.swing.GroupLayout isls301_priceLayout = new javax.swing.GroupLayout(isls301_price);
        isls301_price.setLayout(isls301_priceLayout);
        isls301_priceLayout.setHorizontalGroup(
            isls301_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls301_priceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        isls301_priceLayout.setVerticalGroup(
            isls301_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls301_priceLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deisls301.setBackground(new java.awt.Color(255, 255, 204));
        deisls301.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deisls301.setText("-");

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setForeground(new java.awt.Color(255, 153, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("AR JULIAN", 0, 24)); // NOI18N
        jLabel12.setText("home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jcomskills.setBackground(new java.awt.Color(102, 102, 255));
        jcomskills.setForeground(new java.awt.Color(255, 51, 51));
        jcomskills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcomskillsMouseClicked(evt);
            }
        });

        incgraphics.setBackground(new java.awt.Color(255, 255, 204));
        incgraphics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incgraphics.setText("+");
        incgraphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incgraphicsActionPerformed(evt);
            }
        });

        decarab101.setBackground(new java.awt.Color(255, 255, 204));
        decarab101.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decarab101.setText("-");

        arab101_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("31 SR");

        javax.swing.GroupLayout arab101_priceLayout = new javax.swing.GroupLayout(arab101_price);
        arab101_price.setLayout(arab101_priceLayout);
        arab101_priceLayout.setHorizontalGroup(
            arab101_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab101_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        arab101_priceLayout.setVerticalGroup(
            arab101_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab101_priceLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(530, 530, 530))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(441, 441, 441)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(deisls301)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isls301_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inccomskills))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(decarab201)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(arab201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(incobject))
                                                    .addComponent(jobject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel7))
                                            .addComponent(jcomskills, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jgraphics, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(decisls401)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(isls401_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(incnetwork))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(decarab101)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(arab101_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(incgraphics)))
                                            .addComponent(jnetwork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(587, 587, 587)
                                        .addComponent(decisls201)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isls201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incarchitecture))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(816, 816, 816)
                        .addComponent(jarchitecture, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jobject, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(arab201_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incobject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decarab201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jarchitecture, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(jnetwork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(isls401_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decisls401, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decisls201, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(incnetwork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(isls201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(incarchitecture, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcomskills, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jgraphics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(incgraphics, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(arab101_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decarab101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(inccomskills, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(deisls301, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(isls301_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incobjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incobjectMouseClicked

        if(avaobject==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incobjectMouseClicked

    private void incarchitectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incarchitectureActionPerformed

        if(avaarchitecture==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incarchitectureActionPerformed

    private void incnetworkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incnetworkMouseClicked

        if(avanetwork==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incnetworkMouseClicked

    private void incnetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incnetworkActionPerformed

        if(avanetwork==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incnetworkActionPerformed

    private void inccomskillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inccomskillsActionPerformed

        if(avaskills==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_inccomskillsActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        selectbookstore sn = new selectbookstore();
        sn.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void incgraphicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incgraphicsActionPerformed

        if(avagraphics==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incgraphicsActionPerformed

    private void jobjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobjectMouseClicked
              try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book1);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jobjectMouseClicked

    private void jnetworkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnetworkMouseClicked
             try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book2);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jnetworkMouseClicked

    private void jarchitectureMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jarchitectureMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jarchitectureMouseDragged

    private void jarchitectureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jarchitectureMouseClicked
           try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book5);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jarchitectureMouseClicked

    private void jgraphicsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jgraphicsMouseClicked
        try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book3);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jgraphicsMouseClicked

    private void jcomskillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcomskillsMouseClicked
             try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book4);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jcomskillsMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
              String searchBook = search.getText();
    
        SearchBook_Interface bi = new SearchBook_Interface();
        switch (searchBook) {
  
            case "object oreiented programing":
                bi.displayBook(book1);
                bi.setVisible(true);
                break;
            case "computer networks":
            case "network":
            case "top down networking":
                bi.displayBook(book2);
                bi.setVisible(true);
                break;
            case "graphics":
            case "computer graphics":
                bi.displayBook(book3);
                bi.setVisible(true);
                break;
                  
                     default: SearchBook_noresults n = new SearchBook_noresults();
                  n.setVisible(true);
            case "computer skills" : 
         
                bi.displayBook(book4);
                bi.setVisible(true);break;
            case "computer architecture and organization":
            case "acrchitecture":
                bi.displayBook(book5);
                bi.setVisible(true);break;
            
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fcit_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fcit_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fcit_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fcit_alhafez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fcit_alhafez().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(fcit_alhafez.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arab101_price;
    private javax.swing.JPanel arab201_price;
    private javax.swing.JPanel cart;
    private javax.swing.JButton decarab101;
    private javax.swing.JButton decarab201;
    private javax.swing.JButton decisls201;
    private javax.swing.JButton decisls401;
    private javax.swing.JButton deisls301;
    private javax.swing.JButton incarchitecture;
    private javax.swing.JButton inccomskills;
    private javax.swing.JButton incgraphics;
    private javax.swing.JButton incnetwork;
    private javax.swing.JButton incobject;
    private javax.swing.JPanel info;
    private javax.swing.JPanel isls201_price;
    private javax.swing.JPanel isls301_price;
    private javax.swing.JPanel isls401_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jarchitecture;
    private javax.swing.JLabel jcomskills;
    private javax.swing.JLabel jgraphics;
    private javax.swing.JLabel jnetwork;
    private javax.swing.JLabel jobject;
    private javax.swing.JPanel orders;
    private javax.swing.JTextPane search;
    // End of variables declaration//GEN-END:variables
}
