/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KAUBookStoreSystem;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author manar
 */
public class MainHome extends javax.swing.JFrame {

    /**
     * Creates new form MainHome
     */
    public MainHome() throws FileNotFoundException {
        initComponents();
    
                     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ID = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        email = new javax.swing.JTextPane();
        passwordEmp = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        signSTD = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        signEmp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordSTD = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2809, 897));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel2.setFont(new java.awt.Font("AR JULIAN", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("welcome");

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("ثة");

        panel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("AR JULIAN", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("employee");

        jScrollPane1.setViewportView(ID);

        jScrollPane2.setViewportView(email);

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));

        signSTD.setBackground(new java.awt.Color(153, 255, 153));
        signSTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signSTDMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        jLabel10.setText("sign in");

        javax.swing.GroupLayout signSTDLayout = new javax.swing.GroupLayout(signSTD);
        signSTD.setLayout(signSTDLayout);
        signSTDLayout.setHorizontalGroup(
            signSTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signSTDLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        signSTDLayout.setVerticalGroup(
            signSTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signSTDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        signEmp.setBackground(new java.awt.Color(255, 204, 102));
        signEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signEmpMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        jLabel1.setText("sign in");

        javax.swing.GroupLayout signEmpLayout = new javax.swing.GroupLayout(signEmp);
        signEmp.setLayout(signEmpLayout);
        signEmpLayout.setHorizontalGroup(
            signEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signEmpLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        signEmpLayout.setVerticalGroup(
            signEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        passwordSTD.setFont(new java.awt.Font("AR JULIAN", 1, 18)); // NOI18N
        passwordSTD.setForeground(new java.awt.Color(255, 255, 204));
        passwordSTD.setText(" password");

        jLabel6.setFont(new java.awt.Font("AR JULIAN", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("student");

        jLabel7.setFont(new java.awt.Font("AR JULIAN", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText(" email");

        jLabel8.setFont(new java.awt.Font("AR JULIAN", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("AR JULIAN", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setText("password");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(signEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signSTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(39, 39, 39)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordSTD)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(274, 274, 274))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(37, 37, 37)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordSTD)
                    .addComponent(jLabel9))
                .addGap(54, 54, 54)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signSTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(597, 597, 597)
                        .addComponent(jLabel2)))
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1710, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signSTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signSTDMouseClicked
Login login = new Login();
int check=0;
int notKAU=1;
        if( login.isKAUemail(email.getText())==true ){
           check=1;
           notKAU=0;
        }     
        else{
            check=0;
                   notKAU=1;            
                UIManager.put("OptionPane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("Button.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
 UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "AR JULIAN", Font.BOLD, 16)));
        JOptionPane.showMessageDialog(null,"please enter a KAU email", "",JOptionPane.INFORMATION_MESSAGE);
        }
        if(login.isCorrectPasswordSTD(jPasswordField2.getText())==true){
           check=1;
        }
               if(notKAU==0&& login.isCorrectPasswordSTD(jPasswordField2.getText())==true){
                check=1;
            }else if(notKAU==1){
                check=0;
            }else{
            check=0;
               UIManager.put("OptionPane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("Button.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
 UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "AR JULIAN", Font.BOLD, 16)));
        JOptionPane.showMessageDialog(null,"incorrect password", "",JOptionPane.INFORMATION_MESSAGE);
        }
        if(check==1){
            signin sn = new signin();
            sn.setVisible(true);
        }
             
    }//GEN-LAST:event_signSTDMouseClicked

    private void signEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signEmpMouseClicked
   Login login = new Login();
int check=0;
     int notEmp=1;
        try {
            if( login.isEmployee(ID.getText())==true ){
                check=1;
                notEmp=0;
            }
            else{
                check=0;
                notEmp=1;
                UIManager.put("OptionPane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("Button.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.WHITE);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                        "AR JULIAN", Font.BOLD, 16)));
                JOptionPane.showMessageDialog(null,"Sorry, you're are not an employee", "",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(notEmp==0&&login.isCorrectPasswordEmp(passwordEmp.getText(),ID.getText())==true){
                check=1;
            }else if(notEmp==1){
                check=0;
                
            }else{
                check=0;
                 UIManager.put("OptionPane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("Button.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("Panel.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageForeground", Color.WHITE);
                UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
                UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
                UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                        "AR JULIAN", Font.BOLD, 16)));
                JOptionPane.showMessageDialog(null,"incorrect password", "",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainHome.class.getName()).log(Level.SEVERE, null, ex);
}        if(check==1){
         addbook ad;
       try {
           ad = new addbook();
           ad.setVisible(true);
       } catch (IOException ex) {
           Logger.getLogger(MainHome.class.getName()).log(Level.SEVERE, null, ex);
       }
         
        }
    }//GEN-LAST:event_signEmpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainHome().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ID;
    private javax.swing.JTextPane email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField passwordEmp;
    private javax.swing.JLabel passwordSTD;
    private javax.swing.JPanel signEmp;
    private javax.swing.JPanel signSTD;
    // End of variables declaration//GEN-END:variables
}
