/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KAUBookStoreSystem;

import cpit380practice.*;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;


import cpit380practice.Picture;

/**
 *
 * @author manar
 */
public class media_alhu extends javax.swing.JFrame {
//pictures of the book
static Picture comm1;
static Picture comm2;
static Picture genop;
static Picture politics1;
static Picture politics2;

//to check availablity of book
static boolean avacomm1;
static boolean avacomm2;
static boolean avapolitics1;
static boolean avapolitics2;
static boolean avagenop;
//books
static Book book;
static Book book1;
static Book book2;
static Book book3;
static Book book4;
static Book book5;
    /**
     * Creates new form media_alhu
     */
    public media_alhu() throws FileNotFoundException, FileNotFoundException {
        initComponents();
             cart.setBackground(new Color(255, 255, 255, 100));
        orders.setBackground(new Color(255, 255, 255, 100));
        info.setBackground(new Color(255, 255, 255, 100));
              File file = new File("Book.txt");
        Scanner read = new Scanner (file);
        boolean ava=false;
        Book_linkedlist bl = new Book_linkedlist();
        Book book = new Book();
      while(read.hasNext()){
          switch(read.next()){
              case "404" : 
        String info [] = read.next().split(",");
        comm1 = new Picture ("com.jpg");
    String bookName = info[1] + " " + info[2];
          {
              try {
                  if(book.isAvailable(info[7])==true){
                      avacomm1=true;
                  }else{
                      avacomm1=false;
                  }     } catch (FileNotFoundException ex) {
                  Logger.getLogger(media_alhu.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
        jcomm1.setIcon(new ImageIcon(comm1.getImage().getScaledInstance(160, 160, 1)));
         book1 = new Book(bookName,info[3],info[4],avacomm1,info[5],comm1);
        bl.addBook(book1);
        break;
              case "500" :
    String info1 [] = read.next().split(",");
        politics1 = new Picture ("political.jpg");
        String bookName1= info1[1] + " " + info1[2];
        if(book.isAvailable(info1[7])==true){
            avapolitics1=true;
        }else{
            avapolitics1=false;
        }
         book2 = new Book(bookName1,info1[3],info1[4],avapolitics1,info1[5],politics1);
           jpolitics1.setIcon(new ImageIcon(politics1.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book2);
        break;
         case "501" :  String info2 [] = read.next().split(",");
         genop = new Picture ("generalopinion.jpg");
         String bookName2 = info2[1] + " " + info2[2];
        if(book.isAvailable(info2[7])==true){
            avagenop=true;
          
        }else{
            avagenop=false;
      
        }
       
         book3 = new Book(bookName2,info2[3],info2[4],avagenop,info2[5],genop);
           jgenop.setIcon(new ImageIcon(genop.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book3);
         break;
            case "502" :  String info3 [] = read.next().split(",");
        comm2= new Picture ("comm.jpg");
        String bookName3= info3[1] + " " + info3[2];
        if(book.isAvailable(info3[6])==true){
            avacomm2=true;
        }else{
            avacomm2=false;
        }
         book4 = new Book(bookName3,info3[3],info3[4],avacomm2,info3[5],comm2);
           jcomm2.setIcon(new ImageIcon(comm2.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book4);break;
            case "503" :  String info4 [] = read.next().split(",");
        politics2 = new Picture ("politics.jpg");
        String bookName4 = info4[1] + " " + info4[2];
        if(book.isAvailable(info4[7])==true){
            avapolitics2=true;
        }else{
            avapolitics2=false;
        }
         book5 = new Book(bookName4,info4[3],info4[4],avapolitics2,info4[5],politics2);
           jpolitics2.setIcon(new ImageIcon(politics2.getImage().getScaledInstance(160, 160, 1)));
        bl.addBook(book5);break;
    }
      }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        orders = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcomm1 = new javax.swing.JLabel();
        inccomm1 = new javax.swing.JButton();
        decarab201 = new javax.swing.JButton();
        arab201_price = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jgenop = new javax.swing.JLabel();
        incgenop = new javax.swing.JButton();
        isls401_price = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        decisls401 = new javax.swing.JButton();
        jcomm2 = new javax.swing.JLabel();
        inccomm2 = new javax.swing.JButton();
        isls201_price = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        decisls201 = new javax.swing.JButton();
        jpolitics2 = new javax.swing.JLabel();
        incpolitics1 = new javax.swing.JButton();
        isls301_price = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        deisls301 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpolitics1 = new javax.swing.JLabel();
        incpolitics2 = new javax.swing.JButton();
        decarab101 = new javax.swing.JButton();
        arab101_price = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("AR JULIAN", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("ثة");

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cart.setBackground(new java.awt.Color(255, 204, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cart");

        javax.swing.GroupLayout cartLayout = new javax.swing.GroupLayout(cart);
        cart.setLayout(cartLayout);
        cartLayout.setHorizontalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartLayout.setVerticalGroup(
            cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        orders.setBackground(new java.awt.Color(255, 204, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Orders");

        javax.swing.GroupLayout ordersLayout = new javax.swing.GroupLayout(orders);
        orders.setLayout(ordersLayout);
        ordersLayout.setHorizontalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(78, 78, 78))
        );
        ordersLayout.setVerticalGroup(
            ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        info.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Information");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(search);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("AR JULIAN", 0, 18)); // NOI18N
        jLabel5.setText("search");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jcomm1.setBackground(new java.awt.Color(102, 102, 255));
        jcomm1.setForeground(new java.awt.Color(255, 51, 51));
        jcomm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcomm1MouseClicked(evt);
            }
        });

        inccomm1.setBackground(new java.awt.Color(255, 255, 204));
        inccomm1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inccomm1.setText("+");
        inccomm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inccomm1MouseClicked(evt);
            }
        });

        decarab201.setBackground(new java.awt.Color(255, 255, 204));
        decarab201.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decarab201.setText("-");

        arab201_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("39 SR");

        javax.swing.GroupLayout arab201_priceLayout = new javax.swing.GroupLayout(arab201_price);
        arab201_price.setLayout(arab201_priceLayout);
        arab201_priceLayout.setHorizontalGroup(
            arab201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab201_priceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        arab201_priceLayout.setVerticalGroup(
            arab201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab201_priceLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jgenop.setBackground(new java.awt.Color(102, 102, 255));
        jgenop.setForeground(new java.awt.Color(255, 51, 51));
        jgenop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jgenopMouseClicked(evt);
            }
        });

        incgenop.setBackground(new java.awt.Color(255, 255, 204));
        incgenop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incgenop.setText("+");
        incgenop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incgenopActionPerformed(evt);
            }
        });

        isls401_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("31 SR");

        javax.swing.GroupLayout isls401_priceLayout = new javax.swing.GroupLayout(isls401_price);
        isls401_price.setLayout(isls401_priceLayout);
        isls401_priceLayout.setHorizontalGroup(
            isls401_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls401_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        isls401_priceLayout.setVerticalGroup(
            isls401_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls401_priceLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decisls401.setBackground(new java.awt.Color(255, 255, 204));
        decisls401.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisls401.setText("-");

        jcomm2.setBackground(new java.awt.Color(102, 102, 255));
        jcomm2.setForeground(new java.awt.Color(255, 51, 51));
        jcomm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcomm2MouseClicked(evt);
            }
        });

        inccomm2.setBackground(new java.awt.Color(255, 255, 204));
        inccomm2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inccomm2.setText("+");
        inccomm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inccomm2MouseClicked(evt);
            }
        });
        inccomm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inccomm2ActionPerformed(evt);
            }
        });

        isls201_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("31 SR");

        javax.swing.GroupLayout isls201_priceLayout = new javax.swing.GroupLayout(isls201_price);
        isls201_price.setLayout(isls201_priceLayout);
        isls201_priceLayout.setHorizontalGroup(
            isls201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls201_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        isls201_priceLayout.setVerticalGroup(
            isls201_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls201_priceLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decisls201.setBackground(new java.awt.Color(255, 255, 204));
        decisls201.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decisls201.setText("-");

        jpolitics2.setBackground(new java.awt.Color(102, 102, 255));
        jpolitics2.setForeground(new java.awt.Color(255, 51, 51));
        jpolitics2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpolitics2MouseClicked(evt);
            }
        });

        incpolitics1.setBackground(new java.awt.Color(255, 255, 204));
        incpolitics1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incpolitics1.setText("+");
        incpolitics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incpolitics1ActionPerformed(evt);
            }
        });

        isls301_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("31 SR");

        javax.swing.GroupLayout isls301_priceLayout = new javax.swing.GroupLayout(isls301_price);
        isls301_price.setLayout(isls301_priceLayout);
        isls301_priceLayout.setHorizontalGroup(
            isls301_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls301_priceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        isls301_priceLayout.setVerticalGroup(
            isls301_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isls301_priceLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deisls301.setBackground(new java.awt.Color(255, 255, 204));
        deisls301.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deisls301.setText("-");

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setForeground(new java.awt.Color(255, 153, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("AR JULIAN", 0, 24)); // NOI18N
        jLabel12.setText("home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        jpolitics1.setBackground(new java.awt.Color(102, 102, 255));
        jpolitics1.setForeground(new java.awt.Color(255, 51, 51));
        jpolitics1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpolitics1MouseClicked(evt);
            }
        });

        incpolitics2.setBackground(new java.awt.Color(255, 255, 204));
        incpolitics2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        incpolitics2.setText("+");
        incpolitics2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incpolitics2ActionPerformed(evt);
            }
        });

        decarab101.setBackground(new java.awt.Color(255, 255, 204));
        decarab101.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decarab101.setText("-");

        arab101_price.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("31 SR");

        javax.swing.GroupLayout arab101_priceLayout = new javax.swing.GroupLayout(arab101_price);
        arab101_price.setLayout(arab101_priceLayout);
        arab101_priceLayout.setHorizontalGroup(
            arab101_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab101_priceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        arab101_priceLayout.setVerticalGroup(
            arab101_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arab101_priceLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(530, 530, 530))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(441, 441, 441)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(deisls301)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isls301_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(incpolitics1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(609, 609, 609)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(decarab201)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(arab201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inccomm1))
                                    .addComponent(jcomm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7))
                            .addComponent(jpolitics1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcomm2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jpolitics2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(decisls401)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(isls401_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inccomm2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(decarab101)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(arab101_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(incpolitics2))))
                        .addGap(60, 60, 60)
                        .addComponent(decisls201)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isls201_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incgenop))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(816, 816, 816)
                        .addComponent(jgenop, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jcomm1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(arab201_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inccomm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decarab201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jgenop, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(jcomm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(isls401_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decisls401, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inccomm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(decisls201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(isls201_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incgenop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpolitics1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jpolitics2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incpolitics2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(arab101_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decarab101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(incpolitics1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deisls301, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(isls301_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inccomm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inccomm1MouseClicked

        if(avacomm1==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_inccomm1MouseClicked

    private void incgenopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incgenopActionPerformed

        if(avagenop==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incgenopActionPerformed

    private void inccomm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inccomm2MouseClicked

        if(avacomm2==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_inccomm2MouseClicked

    private void inccomm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inccomm2ActionPerformed

        if(avacomm2==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_inccomm2ActionPerformed

    private void incpolitics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incpolitics1ActionPerformed

        if(avapolitics1==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incpolitics1ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        selectbookstore sn = new selectbookstore();
        sn.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void incpolitics2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incpolitics2ActionPerformed

        if(avapolitics2==false){
            UIManager.put("OptionPane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("Button.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
            UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
            UIManager.put("Panel.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageForeground", Color.WHITE);
            UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
            UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
            UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "AR JULIAN", Font.BOLD, 16)));
    JOptionPane.showMessageDialog(null,"Sorry, This book isn't available", "",JOptionPane.INFORMATION_MESSAGE);
    }else{
        UIManager.put("OptionPane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.RED);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("Button.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageBackground", Color.DARK_GRAY);
        UIManager.put("OptionPane.textbackground", Color.DARK_GRAY);
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", Color.WHITE);
        UIManager.put("OptionPane.warningDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.warningDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.questionDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.border.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.foreground", Color.DARK_GRAY);
        UIManager.put("OptionPane.errorDialog.titlePane.shadow", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
            "AR JULIAN", Font.BOLD, 16)));
JOptionPane.showMessageDialog(null,"book is added to cart", "",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_incpolitics2ActionPerformed

    private void jcomm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcomm1MouseClicked
        try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book1);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jcomm1MouseClicked

    private void jcomm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcomm2MouseClicked
             try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book4);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jcomm2MouseClicked

    private void jgenopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jgenopMouseClicked
             try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book3);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jgenopMouseClicked

    private void jpolitics1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpolitics1MouseClicked
       try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book2);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jpolitics1MouseClicked

    private void jpolitics2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpolitics2MouseClicked
          try {
         BookInterface bi = new BookInterface();
         bi.displayBook(book5);
bi.setVisible(true);
 
    } catch (FileNotFoundException ex) {
        Logger.getLogger(science_alkha.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jpolitics2MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
         String searchBook = search.getText();
        File file = new File("Book.txt");
        SearchBook_Interface bi = new SearchBook_Interface();
        switch (searchBook) {
            case "communication skills":
                bi.displayBook(book1);
                bi.setVisible(true);
                break;
             
            case "media policy":
                bi.displayBook(book2);
                bi.setVisible(true);
                break;
           
            case "general opnion":
                bi.displayBook(book3);
                bi.setVisible(true);
                break;
        
            case "communication skills1":
                bi.displayBook(book4);
                bi.setVisible(true);break;
            
            case "politics":
                bi.displayBook(book5);
                bi.setVisible(true);break;
                      default: SearchBook_noresults n = new SearchBook_noresults();
                  n.setVisible(true);
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(media_alhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(media_alhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(media_alhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(media_alhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new media_alhu().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(media_alhu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel arab101_price;
    private javax.swing.JPanel arab201_price;
    private javax.swing.JPanel cart;
    private javax.swing.JButton decarab101;
    private javax.swing.JButton decarab201;
    private javax.swing.JButton decisls201;
    private javax.swing.JButton decisls401;
    private javax.swing.JButton deisls301;
    private javax.swing.JButton inccomm1;
    private javax.swing.JButton inccomm2;
    private javax.swing.JButton incgenop;
    private javax.swing.JButton incpolitics1;
    private javax.swing.JButton incpolitics2;
    private javax.swing.JPanel info;
    private javax.swing.JPanel isls201_price;
    private javax.swing.JPanel isls301_price;
    private javax.swing.JPanel isls401_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcomm1;
    private javax.swing.JLabel jcomm2;
    private javax.swing.JLabel jgenop;
    private javax.swing.JLabel jpolitics1;
    private javax.swing.JLabel jpolitics2;
    private javax.swing.JPanel orders;
    private javax.swing.JTextPane search;
    // End of variables declaration//GEN-END:variables
}
